/**
 * Turkish UI text constants
 */

export const NAV = {
  dashboard: 'Ana Sayfa',
  trucks: 'Araçlar',
  trips: 'Seferler',
  invoices: 'Ödemeler',
  drivers: 'Şoförler',
  clients: 'Müşteriler',
  more: 'Daha Fazla',
} as const;

export const DASHBOARD = {
  title: 'Kontrol Paneli',
  revenue: 'Bu Ay Gelir',
  outstanding: 'Bekleyen Ödemeler',
  overdue: 'Vadesi Geçmiş',
  profit: 'Net Kâr',
  activeTrips: 'Aktif Seferler',
  availableTrucks: 'Müsait Araçlar',
  availableDrivers: 'Müsait Şoförler',
} as const;

export const TRUCKS = {
  title: 'Araçlar',
  available: 'Müsait',
  inTransit: 'Yolda',
  maintenance: 'Bakımda',
  all: 'Tümü',
  plateNumber: 'Plaka',
  type: 'Tür',
  status: 'Durum',
  driver: 'Şoför',
  currentTrip: 'Aktif Sefer',
  assignmentInfo: 'Atama Bilgileri',
  recentTrips: 'Son Seferler',
  earnings: 'Kazançlar',
  insurance: 'Sigorta',
  compulsoryInsurance: 'Zorunlu Trafik Sigortası',
  comprehensiveInsurance: 'Kasko',
  inspection: 'Muayene',
  expiryDate: 'Son Geçerlilik Tarihi',
  basicInfo: 'Temel Bilgiler',
  documents: 'Belgeler',
  location: 'Konum',
  performance: 'Performans',
  monthlyRevenue: 'Aylık Gelir',
  tripCount: 'Sefer Sayısı',
  utilization: 'Kullanım Oranı',
} as const;

export const DRIVERS = {
  title: 'Şoförler',
  available: 'Müsait',
  onTrip: 'Seferde',
  offDuty: 'İzinli',
  all: 'Tümü',
  fullName: 'Ad Soyad',
  phone: 'Telefon',
  email: 'E-posta',
  license: 'Ehliyet',
  licenseNumber: 'Ehliyet No',
  licenseClass: 'Ehliyet Sınıfı',
  licenseExpiry: 'Ehliyet Geçerlilik',
  certificates: 'Sertifikalar',
  srcCertificate: 'SRC Belgesi',
  cpcCertificate: 'CPC Belgesi',
  certificateNumber: 'Belge No',
  issueDate: 'Veriliş Tarihi',
  expiryDate: 'Son Geçerlilik',
  emergencyContact: 'Acil Durum İletişim',
  contactInfo: 'İletişim Bilgileri',
  contactName: 'İsim',
  contactPhone: 'Telefon',
  relationship: 'Yakınlık',
  assignedTruck: 'Atanmış Araç',
  status: 'Durum',
} as const;

export const TRIPS = {
  title: 'Seferler',
  active: 'Aktif',
  completed: 'Tamamlanan',
  all: 'Tümü',
  createNew: 'Yeni Sefer Oluştur',
  route: 'Güzergah',
  client: 'Müşteri',
  truck: 'Araç',
  driver: 'Şoför',
  status: 'Durum',
  revenue: 'Gelir',
  expenses: 'Giderler',
  profit: 'Kâr',
  assigned: 'Atandı',
  inTransit: 'Yolda',
  delivered: 'Teslim Edildi',
  tripInfo: 'Sefer Bilgileri',
  financial: 'Mali Bilgiler',
  timeline: 'Zaman Çizelgesi',
  created: 'Oluşturuldu',
  started: 'Başladı',
  completedAt: 'Tamamlandı',
  estimated: 'Tahmini Varış',
  netProfit: 'Net Kâr',
} as const;

export const INVOICES = {
  title: 'Ödemeler ve Faturalar',
  all: 'Tümü',
  overdue: 'Vadesi Geçmiş',
  pending: 'Bekleyen',
  paid: 'Ödenen',
  amount: 'Tutar',
  issueDate: 'Düzenleme',
  dueDate: 'Vade',
  paidDate: 'Ödeme',
  client: 'Müşteri',
  status: 'Durum',
  trips: 'Seferler',
  summary: 'Özet',
  totalOutstanding: 'Toplam Bakiye',
  totalOverdue: 'Toplam Vadesi Geçmiş',
  paidThisMonth: 'Bu Ay Ödenen',
  avgPaymentTime: 'Ort. Ödeme Süresi',
  daysOverdue: 'gün gecikmiş',
  daysUntilDue: 'gün kaldı',
  invoiceDetails: 'Fatura Detayları',
  relatedTrips: 'İlgili Seferler',
  paymentInfo: 'Ödeme Bilgileri',
} as const;

export const CLIENTS = {
  title: 'Müşteriler',
  createInvoice: 'Fatura Oluştur',
  companyName: 'Firma Adı',
  taxId: 'Vergi No',
  contact: 'İletişim',
  outstanding: 'Bakiye',
  totalInvoiced: 'Toplam Faturalanan',
  totalPaid: 'Toplam Ödenen',
  avgPaymentDays: 'Ort. Ödeme Süresi',
  invoices: 'Faturalar',
  tripHistory: 'Sefer Geçmişi',
  paid: 'Ödendi',
  pending: 'Bekliyor',
  overdue: 'Gecikmiş',
} as const;

export const EXPENSES = {
  fuel: 'Yakıt',
  tolls: 'HGS/OGS',
  driverFee: 'Şoför Ücreti',
  other: 'Diğer',
  total: 'Toplam Gider',
} as const;

export const COMMON = {
  save: 'Kaydet',
  cancel: 'İptal',
  edit: 'Düzenle',
  delete: 'Sil',
  search: 'Ara',
  filter: 'Filtrele',
  loading: 'Yükleniyor...',
  noData: 'Veri bulunamadı',
  error: 'Bir hata oluştu',
  success: 'Başarılı',
  currency: '₺',
  days: 'gün',
} as const;

export const DOCUMENTS = {
  title: 'Belgeler',
  upload: 'Belge Yükle',
  deliveryConfirmation: 'Teslimat Onayı',
  uploadPhoto: 'Fotoğraf Yükle',
  takePhoto: 'Fotoğraf Çek',
  maxSize: 'Maks. boyut',
  noDocuments: 'Henüz belge yüklenmemiş',
  documentCount: 'belge',
  uploadedAt: 'Yüklenme',
  maxLimit: 'Maksimum 3 fotoğraf yüklenebilir',
  fileTooLarge: 'Dosya boyutu çok büyük',
  invalidFileType: 'Geçersiz dosya türü',
  uploadSuccess: 'Belge başarıyla yüklendi',
  uploadError: 'Yükleme sırasında hata oluştu',
} as const;

export const WARNINGS = {
  overdueInvoices: 'fatura vadesi geçmiş',
  licenseExpiring: 'ehliyet süresi doluyor',
  documentExpiring: 'belgesi süresi doluyor',
  insuranceExpiring: 'sigorta süresi doluyor',
  inspectionExpiring: 'muayene süresi doluyor',
  certificateExpiring: 'sertifika süresi doluyor',
  daysRemaining: 'gün kaldı',
  expired: 'Süresi dolmuş',
  expiringSoon: 'Yakında sona eriyor',
  valid: 'Geçerli',
} as const;
